Release/6.4.0
onfido/onfido-sdk-ui pull request #1280
Opened 2020-12-17 12:55 UTC by stefaniacardenas

## 6.4.0

### Added

- Internal: Introduce Hooks on non-critical components.
- Public: Added `CROSS_DEVICE_INTRO`, `CROSS_DEVICE_GET_LINK` user analytic events for integrators to listen for when tracking user journey when initiating Cross Device flow from desktop browser
- Public: Added `licenses.json` file containing the list of dependencies licenses.

### Changed

- UI: User is no longer blocked from uploading an image file over 10MB in size. Instead image is resized to 720p if file size is over 3MB.
- Internal: Update SDK's Publish Release workflow to not use the now deprecated `set-env` command.

### Fixed

- Public: Fixed issue where the SDK could not be initialised with `poa` as a single step.
- Public: Only return `Missing keys` warning for unsupported language locale tags

2020-12-17 13:18 UTC, ethan605 requested changes
Generally LGTM, just one strange diff confuses me a bit:
![Swappshot Thu Dec 17 13:16:22 2020](https://user-images.githubusercontent.com/1215541/102492885-3a138180-406a-11eb-98fe-bc39b592f671.png)
I can't find the commit `ae5439` nor `web-audio-recording` in the latest `development` branch

2020-12-17 13:30 UTC, stefaniacardenas commented
Good spot @ethan605, that was committed by mistake by the release script. It was a PoC I did locally. I will remove it

2020-12-17 13:34 UTC, ethan605 approved these changes

2020-12-17 14:58 UTC, rfreitas commented
Travis automatic deployment: https://staging-1280-pr-onfido-sdk-ui-onfido.surge.sh

2020-12-17 14:58 UTC, rfreitas commented
Travis automatic deployment: https://release-1280-pr-onfido-sdk-ui-onfido.surge.sh

2020-12-17 15:07 UTC, rfreitas commented
Travis automatic deployment: https://1280-pr-onfido-sdk-ui-onfido.surge.sh

2020-12-21 10:22 UTC, kopijunkie approved these changes

2020-12-21 14:14 UTC, rfreitas commented
Travis automatic deployment: https://staging-1280-pr-onfido-sdk-ui-onfido.surge.sh

2020-12-21 14:19 UTC, rfreitas commented
Travis automatic deployment: https://release-1280-pr-onfido-sdk-ui-onfido.surge.sh

2020-12-21 14:31 UTC, rfreitas commented
Travis automatic deployment: https://1280-pr-onfido-sdk-ui-onfido.surge.sh

2020-12-21 14:57 UTC, merged