Add babel Typescript preset
onfido/onfido-sdk-ui pull request #1319
Opened 2021-01-25 16:36 UTC by kopijunkie

# Problem
The [development branch Surge link](https://development-branch-onfido-sdk-ui-onfido.surge.sh/) is no longer rendering on IE11. This issue is not happening for the [latest production Surge link](https://latest-onfido-sdk-ui-onfido.surge.sh/), so it is a dev regression following latest merged work, most likely the Typescript conversion. 

# Solution

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [n/a] Has the CHANGELOG been updated? _(dev regression)_
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

2021-01-25 16:41 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-25 16:42 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-25 16:53 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-25 18:15 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-25 18:16 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-25 18:24 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 09:51 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 09:53 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 10:01 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 10:44 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 10:49 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 10:55 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 11:19 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 11:23 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 11:29 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 11:38 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 11:39 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-26 11:45 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 09:17 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 09:17 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 09:24 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 10:26 UTC, ethan605 requested changes

2021-01-27 10:26 UTC, ethan605 commented on src/demo/demo.ejs
>        script-src 'self' https://www.woopra.com https://assets.onfido.com https://sentry.io;
For local development environment, the CSP complains about missing the polyfill from `script-src`:
```suggestion
      script-src 'self' https://www.woopra.com https://assets.onfido.com https://sentry.io https://cdn.polyfill.io/v3/polyfill.min.js;
```

2021-01-27 11:06 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 11:11 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 11:17 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 13:19 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 13:22 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-27 17:21 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 16:07 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 16:08 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 16:15 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 16:35 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 16:36 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 16:45 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 16:56 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 16:57 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 17:04 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 17:14 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 17:14 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 18:05 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 18:05 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-28 18:15 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 12:31 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 12:36 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 12:44 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 14:00 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 14:05 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 14:11 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 15:19 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 15:19 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 15:30 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 15:47 UTC, rfreitas commented
Travis automatic deployment: https://release-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 15:47 UTC, rfreitas commented
Travis automatic deployment: https://staging-1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-01-29 15:52 UTC, rfreitas commented
Travis automatic deployment: https://1319-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-01 11:18 UTC, ethan605 approved these changes

2021-02-01 17:57 UTC, stefaniacardenas approved these changes

2021-02-02 17:19 UTC, merged