Release/6.5.0
onfido/onfido-sdk-ui pull request #1326
Opened 2021-02-03 17:30 UTC by kopijunkie

### Added

- Public: Added npm latest version badge.
- Internal: Now the UI tests will hit API endpoints from a dockerised mock server.
- Internal: Introduce TypeScript on non-critical components & deprecate FlowType.
- Internal: Introduce integration tests for API endpoint integrations.

### Changed

- Internal: Switched to `bundlewatch` Github Action for bundle size diff reporting, checking.
- UI: Updated text and background colours.
- Public: Removed references to MIT license in README and updated copy in LICENSE to refer to Onfido Service Agreement and 3rd party licenses reports.
- Public: Return error for image quality failures on the first two document upload attempts.

### Fixed

- Public: Fix "File type not supported" error on snapshot upload in selfie step.
- Public: Fix typo in `en_US.json` file

2021-02-03 17:37 UTC, rfreitas commented
Travis automatic deployment: https://staging-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-03 17:41 UTC, rfreitas commented
Travis automatic deployment: https://release-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-03 17:58 UTC, rfreitas commented
Travis automatic deployment: https://release-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-03 17:58 UTC, rfreitas commented
Travis automatic deployment: https://staging-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-03 18:07 UTC, rfreitas commented
Travis automatic deployment: https://1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-04 10:54 UTC, ethan605 requested changes

2021-02-04 10:54 UTC, ethan605 commented on MIGRATION.md
> +## `6.x.y` -> `7.0.0`
I forgot to update this
```suggestion
## `6.4.0` -> `6.5.0`
```

2021-02-04 10:54 UTC, ethan605 commented on MIGRATION.md
> +From version 7.0.0, TypeScript is officially supported. If you previously installed
```suggestion
From version 6.5.0, TypeScript is officially supported. If you previously installed
```

2021-02-04 10:54 UTC, ethan605 commented on README.md
> +From version `7.0.0`, TypeScript is officially supported, providing typings for:
```suggestion
From version `6.5.0`, TypeScript is officially supported, providing typings for:
```

2021-02-04 14:27 UTC, rfreitas commented
Travis automatic deployment: https://release-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-04 14:36 UTC, rfreitas commented
Travis automatic deployment: https://staging-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-04 14:39 UTC, rfreitas commented
Travis automatic deployment: https://release-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-04 14:48 UTC, rfreitas commented
Travis automatic deployment: https://1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-04 17:34 UTC, rfreitas commented
Travis automatic deployment: https://staging-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-04 17:39 UTC, rfreitas commented
Travis automatic deployment: https://release-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-04 17:46 UTC, rfreitas commented
Travis automatic deployment: https://1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-08 10:34 UTC, ethan605 approved these changes
LGTM!

2021-02-08 11:32 UTC, stefaniacardenas approved these changes

2021-02-08 12:22 UTC, rfreitas commented
Travis automatic deployment: https://staging-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-08 12:27 UTC, rfreitas commented
Travis automatic deployment: https://release-1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-08 12:33 UTC, rfreitas commented
Travis automatic deployment: https://1326-pr-onfido-sdk-ui-onfido.surge.sh

2021-02-08 12:58 UTC, merged