Use Node 14 LTS (fermium) on Travis
onfido/onfido-sdk-ui pull request #1370
Opened 2021-03-12 15:48 UTC by ethan605

# Problem

Currently in `.nvmrc` and `Dockerfile` we're using Node 14, while for Travis we're using Node 10

# Solution

Update to use Node 14 on Travis-CI

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [n/a] Has the CHANGELOG been updated?
- [n/a] Has the README been updated?
- [n/a] Has the CONTRIBUTING doc been updated?
- [n/a] Has the RELEASE_GUIDELINES been updated?
- [n/a] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [n/a] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [n/a] Have any new automated tests been implemented or the existing ones changed?
- [n/a] Have any new manual tests been written down or the existing ones changed?
- [n/a] Have any new strings been translated or the existing ones changed?

2021-03-12 15:54 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-12 15:54 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-12 16:17 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-12 16:17 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-12 16:27 UTC, rfreitas commented
Travis automatic deployment: https://1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-12 17:08 UTC, kopijunkie approved these changes

2021-03-15 11:20 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-15 11:21 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-15 11:31 UTC, rfreitas commented
Travis automatic deployment: https://1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-17 10:50 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-17 10:52 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-17 11:01 UTC, rfreitas commented
Travis automatic deployment: https://1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-18 11:29 UTC, stefaniacardenas requested changes

2021-03-18 11:29 UTC, stefaniacardenas commented on CHANGELOG.md
> +- Internal: Use Node 14 LTS for Travis to be consistent with `.nvmrc` and `Dockerfile`.
These logs have been added to the wrong version

2021-03-18 13:49 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-18 13:54 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-18 14:00 UTC, rfreitas commented
Travis automatic deployment: https://1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 10:45 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 10:45 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 10:52 UTC, rfreitas commented
Travis automatic deployment: https://1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 14:32 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 14:33 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 14:41 UTC, rfreitas commented
Travis automatic deployment: https://1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 19:07 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 19:12 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-19 19:19 UTC, rfreitas commented
Travis automatic deployment: https://1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-22 09:56 UTC, rfreitas commented
Travis automatic deployment: https://release-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-22 09:57 UTC, rfreitas commented
Travis automatic deployment: https://staging-1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-22 10:09 UTC, rfreitas commented
Travis automatic deployment: https://1370-pr-onfido-sdk-ui-onfido.surge.sh

2021-03-22 10:35 UTC, stefaniacardenas approved these changes

2021-03-22 15:35 UTC, merged