README edits (1)
onfido/onfido-sdk-ui pull request #1427
Opened 2021-05-05 14:26 UTC by Phoebe-B

Edits to the following README sections:
• Customising the SDK

Improving structure and language (no content changes).

2021-05-05 14:44 UTC, superdevx64 commented on README.md
> +- [Initilization options](#initilization-options)
Minor: "Initialization" (both times)

2021-05-05 14:44 UTC, superdevx64 commented on README.md
> +## Initilization options
Minor: "Initialization"

2021-05-05 14:51 UTC, superdevx64 commented
General but minor comment which may be out of scope: a few words use British spelling rather than Oxford spelling (ise rather than ize)

2021-05-05 17:50 UTC, kopijunkie requested changes
Just some minor typos, Markdown formatting that needs fixing.

2021-05-05 17:50 UTC, kopijunkie commented on README.md
> +  If `useModal` is set to `true`, by default the user can close the SDK by clicking on the close button or on the background overlay. You can disable the user's ability to close the SDK by clicking t
```suggestion
  If `useModal` is set to `true`, by default the user can close the SDK by clicking on the close button or on the background overlay. You can disable the user's ability to close the SDK by clicking the background overlay through setting `shouldCloseOnOverlayClick` to `false`.
```

2021-05-05 17:50 UTC, kopijunkie commented on README.md
> +  When `forceCrossSevice` is set to `true`, the cross device flow is mandatory for all users. Desktop users will be required to complete the capture process on a mobile device browser.
```suggestion
  When `forceCrossDevice` is set to `true`, the cross device flow is mandatory for all users. Desktop users will be required to complete the capture process on a mobile device browser. 
```

2021-05-18 11:40 UTC, kopijunkie approved these changes

2021-05-18 14:11 UTC, merged