Feature/a11y add role to cross device flow screens' link buttons
onfido/onfido-sdk-ui pull request #1479
Opened 2021-06-17 14:23 UTC by kopijunkie

# Problem
Screen readers do not announce the "Resend link" and "Cancel" buttons as buttons.

# Solution
Add ARIA role `button` to "Resend link" and "Cancel" buttons on Cross Device flow SMS Sent, Mobile Connected screens.

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [x] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the TESTING_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

2021-06-18 07:13 UTC, josokinas approved these changes
It is interesting, that you use an anchor with href of `#` and `onClick`, instead of just using a button.

2021-06-18 09:36 UTC, ethan605 requested changes
LGTM, just a minor suggestion to prefer hook

2021-06-18 09:36 UTC, ethan605 commented on src/components/crossDevice/MobileConnected/index.tsx
> +const MobileConnected: FunctionComponent<Props> = ({ translate, back }) => (
You can use `useLocales()` hook here to avoid passing `translate` prop (and can eliminate `WithLocalisedProps` too) :)

2021-06-18 09:36 UTC, ethan605 commented on src/components/crossDevice/MobileNotificationSent/index.tsx
> +  translate,
Ditto here (`useLocales()` hook over passing `translate` prop)

2021-06-22 09:02 UTC, ethan605 approved these changes
LGTM!

2021-06-22 15:03 UTC, merged