Release/6.10.0
onfido/onfido-sdk-ui pull request #1480
Opened 2021-06-18 14:13 UTC by stefaniacardenas

## 6.10.0

### Added

- Internal: Added note about lockfileVersion and npm version requirement for SDK contributors in CONTRIBUTING.md documentation.
- Public: Added support for Italian `it_IT` and Portuguese `pt_PT`.

### Changed

- UI: Updated default Welcome screen UI
- Public: Move documentation for SDK UI Customizations and Premium Enterprise Features into separate Markdown files to reduce README size
- Public: Updated SDK copy for English (en_US), Spanish (es_ES), French (fr_FR) and German (de_DE). For details on what keys/copy have changed please refer to the MIGRATION.md documentation.

### Fixed

- Internal: Upgrade Preact from version `10.5.4` to `10.5.13` in order to resolve an unhandled exception on reinitialising the SDK after closing the SDK modal for some integrations when using Modal mode.
- Public: Fix Country Selection screen not displaying when SDK is initialised with boolean `documentTypes` configuration.
- Public: Fixed issue where `onComplete` callback was fired without the necessary data for the `face` step. Added exception to `onError` callback to inform that `onComplete` could not be fired due to missing data.

2021-06-21 10:45 UTC, kopijunkie requested changes
Mostly just documentation fixes. Looks like some stray/duplicated release notes & unreleased features ending up in previous releases, most likely from merges.

2021-06-21 10:45 UTC, kopijunkie commented on CHANGELOG.md
> +- Internal: Added support for testing across multiple browsers.
This line seems to be duplicated in line 33 under v6.9.0

2021-06-21 10:45 UTC, kopijunkie commented on CHANGELOG.md
> +- Internal: Added ability to execute/ignore tests via the use of tags/regex.
These feel like they should be under current release. @SherBhachuOnFido these are unreleased changes still, right?

2021-06-21 10:45 UTC, kopijunkie commented on CONTRIBUTING.md
> +| `customWelcomeScreenCopy`  | `true`,`false`      | `false` | Configure welcome screen with custom text                        |
Missing documentation for new `multiDocWithBooleanValues` URL query parameter, think my commit for the change must have been after PR was merged.
```suggestion
| `customWelcomeScreenCopy`  | `true`,`false`      | `false` | Configure welcome screen with custom text                        |
| `multiDocWithBooleanValues`   | `true`,`false`      | `false` | Enable document types with boolean flags                     |
```

2021-06-21 10:45 UTC, kopijunkie commented on MIGRATION.md
> +
Stray duplicated line(s)? 🤔

2021-06-21 14:24 UTC, kopijunkie approved these changes

2021-06-22 09:04 UTC, ethan605 approved these changes

2021-06-22 09:34 UTC, merged