Speed up Github Actions
onfido/onfido-sdk-ui pull request #1598
Opened 2021-10-29 11:28 UTC by stefaniacardenas

# Problem
Currently, our Github Action checks run a lot of redundant commands that take a very long time.

# Solution

- Replace `prepare` command with `prepublishOnly` to run all builds
- Add `prebuild` command to clean the dist state and load pre-commit hooks
- Added a pre-commit hook to test for eslint, styles and format issues before committing
- Added step in our CI build to run `npm run check`

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [ ] Has the CHANGELOG been updated?
- [ ] Has the README been updated?
- [ ] Has the CONTRIBUTING doc been updated?
- [ ] Has the RELEASE_GUIDELINES been updated?
- [ ] Has the TESTING_GUIDELINES been updated?
- [ ] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [ ] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [ ] Have any new automated tests been implemented or the existing ones changed?
- [ ] Have any new manual tests been written down or the existing ones changed?
- [ ] Have any new strings been translated or the existing ones changed?

2021-11-01 10:59 UTC, kopijunkie requested changes

2021-11-01 10:59 UTC, kopijunkie commented on .github/workflows/CI.yml
> +      - name: npm run check
A bit confusing to have the job's name same as the command it's running IMO. 
```suggestion
      - name: Run linters
```

2021-11-01 10:59 UTC, kopijunkie commented on package.json
> +    "prepublish": "npm run build:all",
This script has been deprecated according to the npm docs https://docs.npmjs.com/cli/v7/using-npm/scripts#prepare-and-prepublish I think the script to run is `prepublishOnly` depending on the use case.

2021-11-02 10:09 UTC, kopijunkie approved these changes
LGTM 🚀

2021-11-02 12:58 UTC, ethan605 approved these changes
LGTM

2021-11-03 17:06 UTC, merged