Parallel precommit
onfido/onfido-sdk-ui pull request #1647
Opened 2021-12-08 12:53 UTC by it-ony

# Problem

commit a file takes about a minute, as we run the following checks

* "check:types": "tsc --noEmit --jsx preserve",
* "check:es": "eslint '{src,test}/**/*.{js,jsx,ts,tsx}'",
* "check:styles": "stylelint 'src/**/*.scss'",
* "check:format": "prettier . -c",

This is way to much time and developers might get distracted while waiting for the pre-commit hook to be finished.

# Solution

Run the checks in parallel.

## Checklist

_put `n/a` if item is not relevant to PR changes_

- [n/a] Has the CHANGELOG been updated?
- [n/a] Has the README been updated?
- [n/a] Has the CONTRIBUTING doc been updated?
- [n/a] Has the RELEASE_GUIDELINES been updated?
- [n/a] Has the TESTING_GUIDELINES been updated?
- [n/a] Has the MIGRATION doc been updated for any MAJOR breaking changes?
- [n/a] Has the MIGRATION doc been updated for any MINOR breaking changes, including any translation strings or keys changes?
- [n/a] Have any new automated tests been implemented or the existing ones changed?
- [n/a] Have any new manual tests been written down or the existing ones changed?
- [n/a] Have any new strings been translated or the existing ones changed?

2021-12-08 14:16 UTC, kopijunkie approved these changes

2021-12-08 14:32 UTC, stefaniacardenas requested changes

2021-12-08 14:32 UTC, stefaniacardenas commented on package.json
> +    "concurrently": "^6.4.0",
This should go in `devDependencies` this way it does not get bundled in the production bundle (unless it's invoked in the code)

2021-12-09 15:35 UTC, kopijunkie approved these changes

2021-12-09 15:35 UTC, merged