🚨 Fix warnings
onfido/onfido-sdk-ui pull request #1926
Opened 2022-06-20 20:28 UTC by warrenseine

2022-06-22 08:53 UTC, DannyvanderJagt requested changes

2022-06-22 14:02 UTC, DannyvanderJagt commented on src/components/Confirm/Confirm.tsx
> +  }, [props])
The props shouldn't change when the screen already has been loaded.

2022-06-22 15:27 UTC, warrenseine commented on src/components/Confirm/Confirm.tsx
> +  }, [props])
Agreed, so there's no problem adding it in the dependency array.

2022-06-24 12:17 UTC, DannyvanderJagt commented on src/components/Confirm/Confirm.tsx
> +  }, [props])
In case they do, we now trigger a new analytics event which we shouldn't.

2022-06-27 09:17 UTC, DannyvanderJagt approved these changes
Thanks for changing 👍

2022-06-27 09:17 UTC, merged